Repository team-reviewing/reviewing-frontend, pull requests merged in 2023-05, with the labels that each got.

#26 [#25] 가이드 페이지 틀 생성
  components/Commons/Header.tsx
  components/Guide/ContentBox.tsx
  components/Guide/GuideForm.tsx
  components/Guide/NavListBox.tsx
  components/Guide/NavListItem.tsx
  components/Guide/Template.tsx
  components/HeaderSub/GuideButton.tsx
  pages/_app.tsx
  pages/guide.tsx
Labels: feature

#28 [#27] SSR 후 안티 패턴 제거
  components/InduceLogin/InduceBox.tsx
  components/Main/FilterCategory.tsx
  components/Main/Template.tsx
  components/Main/mainType.ts
  mocks/handlers.ts
  mocks/index.ts
  next.config.js
  pages/_app.tsx
  pages/api/core/index.ts
  pages/index.tsx
Labels: refactor

#30 [#29] 거절 API 변경에 따른 수정
  components/ReviewListSearch/ReviewStatusButtonGroup.tsx
  components/ReviewModal/ReviewModal.tsx
  components/ReviewModal/ReviewSection.tsx
  components/ReviewModal/reviewModalType.ts
  mocks/handlers.ts
  mocks/mockApiData.ts
  pages/api/inquire.ts
Labels: refactor

#32 [#31] 리뷰어 가이드 컴포넌트 구현
  components/Commons/Header.tsx
  components/Guide/ContentBox.tsx
  components/Guide/GuideContent.tsx
  components/Guide/GuideImage.tsx
  components/Guide/GuideSubTitle.tsx
  components/Guide/GuideTitle.tsx
  components/Guide/GuideTitleMent.tsx
  components/Guide/Reviewer/ReviewerGuideImageData.ts
  components/Guide/Reviewer/ReviewerGuideRegister.tsx
  components/Guide/Reviewer/ReviewerGuideReviewList.tsx
  components/Guide/Reviewer/Template.tsx
  components/Guide/Template.tsx
  components/Guide/guideType.ts
  mocks/mockApiData.ts
  package-lock.json
  package.json
  public/guide/reviewAccepted.png
  public/guide/reviewApproved.png
  public/guide/reviewList.png
  public/guide/reviewListModal.png
  public/guide/reviewerRegister.png
  public/guide/reviewerStatus.png
Labels: feature

#34 [#33] 리뷰이 가이드 구현
  components/Guide/ContentBox.tsx
  components/Guide/GuideForm.tsx
  components/Guide/Reviewee/RevieweeGuideImageData.ts
  components/Guide/Reviewee/RevieweeGuideRequest.tsx
  components/Guide/Reviewee/RevieweeGuideSelect.tsx
  components/Guide/Reviewee/RevieweeTemplate.tsx
  components/Guide/Reviewer/ReviewerTemplate.tsx
  package-lock.json
  public/guide/reviewChoose.png
  public/guide/reviewInquire.png
  public/guide/reviewInquireDetail.png
  public/guide/reviewModify.png
  public/guide/reviewRequest.png
  public/guide/reviewRequestWrite.png
Labels: feature

#39 [#36] 리뷰 평가 로직 추가
  components/Commons/Portal.tsx
  components/Commons/StarRate/EmptyStarRate.tsx
  components/Commons/StarRate/FullStarRate.tsx
  components/Commons/StarRate/StarRate.tsx
  components/Commons/StarRate/starRateType.ts
  components/ReviewListSearch/ReviewInquireBox.tsx
  components/ReviewListSearch/ReviewInquireBoxContent.tsx
  components/ReviewListSearch/ReviewListType.ts
  components/ReviewListSearch/ReviewSearchForm.tsx
  components/ReviewRate/ReviewEvaluation.tsx
  components/ReviewRate/ReviewEvaluationButtonGroup.tsx
  components/ReviewRate/ReviewEvaluationContent.tsx
  components/ReviewRate/ReviewRateHeader.tsx
  components/ReviewRate/ReviewRateModal.tsx
  components/ReviewRate/ReviewSuccessRateBox.tsx
  components/ReviewRate/queries/getReviewRateQuery.tsx
  components/ReviewRate/reviewRateType.ts
  mocks/handlers.ts
  mocks/mockApiData.ts
  pages/_document.tsx
  pages/api/reviewRate.ts
Labels: feature

#41 [#40] 리뷰 평가 API 수정
  components/ReviewRate/ReviewEvaluation.tsx
  components/ReviewRate/queries/getReviewRateQuery.tsx
Labels: refactor

#38 [#37] 리뷰어 상세 정보 모달 구현
  components/Commons/StarRate/StarRate.tsx
  components/Commons/StarRate/starRateType.ts
  components/Main/ReviewerCard.tsx
  components/ReviewerModal/ReviewPaginationButton.tsx
  components/ReviewerModal/ReviewerIntro.tsx
  components/ReviewerModal/ReviewerModal.tsx
  components/ReviewerModal/ReviewerScoreListBox.tsx
  components/ReviewerModal/queries/getReviewerModalQuery.tsx
  components/ReviewerModal/reviewerModalType.ts
  mocks/handlers.ts
  mocks/mockApiData.ts
  pages/api/core/index.ts
  pages/api/reviewerDetail.ts
Labels: feature

#42 2.1.0 버전 배포 머지
  components/Commons/Portal.tsx
  components/Commons/StarRate/EmptyStarRate.tsx
  components/Commons/StarRate/FullStarRate.tsx
  components/Commons/StarRate/StarRate.tsx
  components/Commons/StarRate/starRateType.ts
  components/Main/ReviewerCard.tsx
  components/ReviewListSearch/ReviewInquireBox.tsx
  components/ReviewListSearch/ReviewInquireBoxContent.tsx
  components/ReviewListSearch/ReviewListType.ts
  components/ReviewListSearch/ReviewSearchForm.tsx
  components/ReviewRate/ReviewEvaluation.tsx
  components/ReviewRate/ReviewEvaluationButtonGroup.tsx
  components/ReviewRate/ReviewEvaluationContent.tsx
  components/ReviewRate/ReviewRateHeader.tsx
  components/ReviewRate/ReviewRateModal.tsx
  components/ReviewRate/ReviewSuccessRateBox.tsx
  components/ReviewRate/queries/getReviewRateQuery.tsx
  components/ReviewRate/reviewRateType.ts
  components/ReviewerModal/ReviewPaginationButton.tsx
  components/ReviewerModal/ReviewerIntro.tsx
  components/ReviewerModal/ReviewerModal.tsx
  components/ReviewerModal/ReviewerScoreListBox.tsx
  components/ReviewerModal/queries/getReviewerModalQuery.tsx
  components/ReviewerModal/reviewerModalType.ts
  mocks/handlers.ts
  mocks/mockApiData.ts
  pages/_document.tsx
  pages/api/core/index.ts
  pages/api/reviewRate.ts
  pages/api/reviewerDetail.ts
Labels: deployment

#45 [#44] 리뷰 취소하기
  components/ReviewModal/ReviewModal.tsx
  mocks/handlers.ts
  pages/api/inquire.ts
Labels: feature

#46 [#43] 리뷰어 평가 리스트 추가
  components/UserInformation/InformationForm.tsx
  components/UserInformation/ReviewerRateContent.tsx
  components/UserInformation/ReviewerRateHeader.tsx
  components/UserInformation/ReviewerRateModal.tsx
  components/UserInformation/ReviewerRegisterContent.tsx
  components/UserInformation/ReviewerRegisterModals.tsx
  components/UserInformation/queries/getReviewerQuery.tsx
  mocks/handlers.ts
  mocks/mockApiData.ts
  pages/api/userInfo.ts
Labels: feature

#47 2.2.0 버전 배포 머지
  components/ReviewModal/ReviewModal.tsx
  components/UserInformation/InformationForm.tsx
  components/UserInformation/ReviewerRateContent.tsx
  components/UserInformation/ReviewerRateHeader.tsx
  components/UserInformation/ReviewerRateModal.tsx
  components/UserInformation/ReviewerRegisterContent.tsx
  components/UserInformation/ReviewerRegisterModals.tsx
  components/UserInformation/queries/getReviewerQuery.tsx
  mocks/handlers.ts
  mocks/mockApiData.ts
  pages/api/inquire.ts
  pages/api/userInfo.ts
Labels: deployment
