Repository team-reviewing/reviewing-frontend, pull requests merged in 2023-04, with the labels that each got.

#5 [#4] SEO 처리
  components/Commons/HeadHoc.tsx
  components/Commons/commonsType.ts
  pages/_app.tsx
  pages/index.tsx
  pages/induceLogin.tsx
  pages/register.tsx
  pages/reviews.tsx
  pages/user/me.tsx
  public/favicon.ico
  public/review.ico
Labels: feature

#7 [#1] 시멘틱 태그로 수정
  components/Commons/Carousel.tsx
  components/Commons/Header.tsx
  components/HeaderSub/HeaderDropDown.tsx
  components/Main/ReviewerBox.tsx
  components/Main/ReviewerCard.tsx
  components/ReviewListSearch/ReviewInquireBox.tsx
  components/ReviewModal/ReviewModal.tsx
  components/UserInformation/ReviewerRegisterModal.tsx
  pages/index.tsx
  pages/induceLogin.tsx
  pages/register.tsx
  pages/reviews.tsx
  pages/user/me.tsx
Labels: refactor

#11 [#9] 리뷰 목록 페이지 변경
  components/ReviewListSearch/ReviewInquireBox.tsx
  components/ReviewListSearch/ReviewListType.ts
  components/ReviewListSearch/ReviewRoleButtonGroup.tsx
  components/ReviewListSearch/ReviewSearchForm.tsx
  components/ReviewListSearch/ReviewStatusButtonGroup.tsx
  components/ReviewListSearch/queries/getReviewsQuery.tsx
  components/ReviewModal/ReviewModal.tsx
  components/ReviewModal/reviewModalType.ts
  mocks/handlers.ts
  pages/api/inquire.ts
Labels: refactor

#12 [#10] carousel 적용
  components/Commons/Carousel.tsx
  components/Commons/CarouselCard.tsx
  components/Commons/CarouselSwiper.tsx
  components/HeaderSub/HeaderDropDown.tsx
  components/Main/Template.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  styles/globals.css
  styles/images/computer.jpg
  tailwind.config.js
Labels: feature

#14 [#13] 리뷰 완료 로직 구현
  components/ReviewListSearch/ReviewListType.ts
  components/ReviewListSearch/queries/getReviewsQuery.tsx
  components/ReviewModal/ReviewModal.tsx
  components/ReviewModal/reviewModalType.ts
  mocks/handlers.ts
  pages/api/inquire.ts
Labels: feature

#20 README 작성
  README.md
Labels: document
